Run `git prune` after installing plugins
Recent git output after installing many plugins:

    Auto packing the repository in background for optimum performance.
    See "git help gc" for manual housekeeping.
    error: The last gc run reported the following. Please correct the
    root cause and remove .git/gc.log.
    Automatic cleanup will not be performed until the file is removed.

    warning: There are too many unreachable loose objects;
    run 'git prune' to remove them.